### ISSUE TITLE
ERD 설계

### ISSUE THREAD

**Issue by shinjaewon99** [my-pet-life/Final_Project_20Team#2]
![2](https://github.com/my-pet-life/Final_Project_20Team/assets/95893341/762a6643-8c9d-49e3-b23d-30e7939264bb)

**Comment by jsl1113** [comment]
article 에서 soft delete 관련 컬럼 필요할까요 ??

**Comment by shinjaewon99** [comment]
음 구현해 나가면서 하면 좋을듯 하네요
